### ISSUE TITLE
Segfault on adding new location to calendar

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#1017]
#### Expected behaviour
Adding location to calendar works normally

#### Actual behaviour
Panel segfaults on clicking "OK" button in dialog to add location

#### Steps to reproduce the behaviour
Open the calendar popup , it will come up with "locations" selected
click "edit" and then "add" buttons
Select any location
click "OK" and that's when the panel segfaults. When it restarts the location will have been sucessfully added. 
Got this backtrace in gdb:
```
Thread 1 "mate-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff714fadd in g_type_check_instance_is_fundamentally_a ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) thread apply all bt full

Thread 6 (Thread 0x7fffdefff700 (LWP 14569)):
#0  0x00007ffff7fe80c5 in  () at /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff6a8db2f in _dl_catch_exception () at /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7fe7bba in  () at /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff6a8d06d in  () at /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff6a8db2f in _dl_catch_exception () at /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff6a8dbbf in _dl_catch_error () at /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffff6a8d147 in  () at /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007ffff6a8d1d6 in __libc_dlopen_mode () at /lib/x86_64-linux-gnu/libc.so.6
#8  0x00007ffff6a74b9e in  () at /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007ffff6a75498 in __nss_lookup_function () at /lib/x86_64-linux-gnu/libc.so.6
#10 0x00007ffff6a755b2 in __nss_lookup () at /lib/x86_64-linux-gnu/libc.so.6
#11 0x00007ffff6a6758b in getservbyname_r () at /lib/x86_64-linux-gnu/libc.so.6
#12 0x00007ffff6a67173 in getservbyname () at /lib/x86_64-linux-gnu/libc.so.6
#13 0x00007fffecd288eb in libproxy::url::url(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /usr/lib/x86_64-linux-gnu/libproxy.so.1
#14 0x00007fffecd29029 in libproxy::url::is_valid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () at /usr/lib/x86_64-linux-gnu/libproxy.so.1
#15 0x00007fffecd238e2 in  () at /usr/lib/x86_64-linux-gnu/libproxy.so.1
#16 0x00007fffecd23d7d in px_proxy_factory_get_proxies () at /usr/lib/x86_64-linux-gnu/libproxy.so.1
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x00007fffeeee047c in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
#18 0x00007ffff721ddae in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x00007ffff706e0d4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#22 0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fffeec6a700 (LWP 14446)):
#0  0x00007ffff6a4cf59 in syscall () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff708f432 in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70183e1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff706e22a in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7fffef7fe700 (LWP 14445)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7045e0f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff41e0ffd in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.--Type <RET> for more, q to quit, c to continue without paging--
so
#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fffeffff700 (LWP 14444)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7046053 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7281b46 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7ffff4a45700 (LWP 14443)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7045e0f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7045e61 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 (Thread 0x7ffff5037f00 (LWP 14424)):
#0  0x00007ffff714fadd in g_type_check_instance_is_fundamentally_a () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff713097e in g_object_ref () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff797c05a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff712c006 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff7147ba0 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff7148122 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff7559a9f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff7544ca8 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#8  0x00007ffff70464d4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff70459fe in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff7045d80 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff7046053 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff7844fb5 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00005555555789f1 in main ()
(gdb) 

```

#### MATE general version
1.23 from git master

#### Package version
local build from git master as of 9-11-2019

#### Linux Distribution
Debian Unstable last updated Sep 6

#### Link to downstream report of your Distribution
None as this is a local build

**Comment by lukefromdc** [comment]
With new gtk 3.24.11 (plus commits from that point to Sep 12 for proper meson build versioning) and glib 2.62.0 I got what might be a more useful backtrace, looks like problems in glib or gtk itself but not sure:
```

Thread 1 "mate-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff7846315 in gtk_widget_get_request_mode ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
(gdb) thread apply all bt full

Thread 7 (Thread 0x7fffec8dc700 (LWP 29693)):
#0  0x00007fffeee8e3d9 in  () at /lib/x86_64-linux-gnu/libnss_files.so.2
#1  0x00007fffeee8f772 in _nss_files_gethostbyname4_r () at /lib/x86_64-linux-gnu/libnss_files.so.2
#2  0x00007ffff69cfe0a in  () at /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff69d0e37 in getaddrinfo () at /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff71b547d in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007ffff71b1d9e in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007ffff7002274 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7001b9d in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007ffff69e64cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7fffef7fe700 (LWP 29653)):
#0  0x00007ffff69db819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6fd9d0e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6fd9e2f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4174ffd in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007ffff7001b9d in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff69e64cf in clone () at /lib/x86_64-linux-gnu/libc.so.6


Thread 3 (Thread 0x7fffeffff700 (LWP 29652)):
#0  0x00007ffff69db819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6fd9d0e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6fda073 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7215ad6 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff7001b9d in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff69e64cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7ffff49d9700 (LWP 29651)):
#0  0x00007ffff69db819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6fd9d0e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6fd9e2f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6fd9e81 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7001b9d in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff69e64cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff4fcbf00 (LWP 29647)):
#0  0x00007ffff7846315 in gtk_widget_get_request_mode () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0

#1  0x00007ffff76c0059 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#2  0x00007ffff76759d0 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff76c4d35 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff7846339 in gtk_widget_get_request_mode () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff76c0059 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff7675a19 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff76c4d35 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff7846339 in gtk_widget_get_request_mode () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff784645e in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff7846e12 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff78471e5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff767558a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff76cc0f4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff76d0238 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff7675c04 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff7846ca3 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff7846eb1 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff78471e5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff767558a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff76cc0f4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0

#21 0x00007ffff76d0238 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff7675c04 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff7846ca3 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff7846eb1 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff78463e1 in gtk_widget_get_preferred_height () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff7750b7a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff76cc0f4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff76d0238 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff7751450 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff76cc0f4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff76d0238 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff77516d3 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff784671b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff7846eb1 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007ffff78463e1 in gtk_widget_get_preferred_height () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007ffff7911a8a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff784671b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007ffff7846eb1 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff78471e5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007ffff784731d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff7910726 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0

#42 0x00007ffff7917880 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#43 0x00007ffff70c0006 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff70dbc10 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff70dc192 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff76c4af0 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007ffff70c0006 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#48 0x00007ffff70dbc10 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x00007ffff70dc192 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#50 0x00007ffff74ed98f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#51 0x00007ffff74d9ac9 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#52 0x00007ffff6fda4f4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#53 0x00007ffff6fd9a1e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#54 0x00007ffff6fd9da0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007ffff6fda073 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#56 0x00007ffff77a2095 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#57 0x00005555555789f1 in main (argc=<optimized out>, argv=<optimized out>) at main.c:227
        desktopfile = <optimized out>

        context = <optimized out>
        error = 0x0
        display = <optimized out>
        screen = 0x55555562a020
        css = 0x555555813ae0
        provider = 0x555555813ae0
        resource = 0x5555555c5588 "/org/mate/panel/theme/mate-panel.css"
        priority = 1
        found_backend = <optimized out>
(gdb) 
```

**Comment by raveit65** [comment]
New test with:
```
[rave@f31 ~]$ uname -r
5.3.0-1.fc31.x86_64
[rave@f31 ~]$ rpm -qa glib2
glib2-2.62.0-1.fc31.x86_64
[rave@f31 ~]$ rpm -qa gtk3
gtk3-3.24.11-1.fc31.x86_64
[rave@f31 ~]$ rpm -qa mate-panel
mate-panel-1.23.1-1.fc31.x86_64
```
mate-panel is built from released 1.23.1 tarball with support for X11, wayland and in-process-applets (all applets).
But i can't reproduce it. Anything different to your setup?
Maybe the issue is introduced between 1.23.1 tarball and actual master?

**Comment by raveit65** [comment]
Same result with matel-panel built from master and --with-in-process-applets=all
Latest commit is https://github.com/mate-desktop/mate-panel/commit/60894665c424ff487caf294b9cd5f72c753a4a4f

**Comment by lukefromdc** [comment]
I have no idea in the world what is different, what exact glib and GTK versions are you using? Stacktrace does not look like the segfault is from within our code but I'm not skilled enough in reading them to be sure. I do not have gtk and glib debugging symbols installed for space reasons.

**Comment by raveit65** [comment]
I was able reproduce the issue today when adding a location to clock-applet in fedora 32 or 30.
For some reasons it's clear reproducible for me now.
With glib2-2.60.7-3.fc30.x86_64 or glib2-2.64.1-1.fc32.x86_64.rpm

**Comment by raveit65** [comment]
My backtrace is different, here the clock-applet crashes with libsoup, which is a dependency from libmateweather.
1.24 panel from master is build with out-of-process-applets to avoid crashing the whole panel.
```
Core was generated by `/usr/libexec/mate-panel/clock-applet'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f11dbdc7b87 in soup_session_kick_queue (session=0x55d46e9cf8df) at ../libsoup/soup-session.c:2353
2353	../libsoup/soup-session.c: No such file or directory.
[Current thread is 1 (Thread 0x7f11dac80c40 (LWP 15975))]

Thread 1 (Thread 0x7f11dac80c40 (LWP 15975)):
#0  0x00007f11dbdc7b87 in soup_session_kick_queue (session=0x55d46e9cf8df) at ../libsoup/soup-session.c:2353
        session = 0x55d46e9cf8df
        conn = <optimized out>
#1  0x00007f11dbdc7b87 in connection_state_changed (object=0x7f11c000c380 [SoupConnection], param=<optimized out>, user_data=0x55d46e9cf8df) at ../libsoup/soup-session.c:1465
        session = 0x55d46e9cf8df
        conn = <optimized out>
#2  0x00007f11dbdc7b87 in connection_state_changed (object=0x7f11c000c380 [SoupConnection], param=<optimized out>, user_data=0x55d46e9cf8df) at ../libsoup/soup-session.c:1459
        session = 0x55d46e9cf8df
        conn = <optimized out>
#6  0x00007f11dc729973 in <emit signal notify:state on instance 0x7f11c000c380 [SoupConnection]> (instance=instance@entry=0x7f11c000c380, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3447
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffdda655800, reg_save_area = 0x7ffdda655740}}
    #3  0x00007f11dc70c742 in g_closure_invoke (closure=0x55d46f0a0d70, return_value=0x0, n_param_values=2, param_values=0x7ffdda655540, invocation_hint=0x7ffdda6554c0) at ../gobject/gclosure.c:810
                marshal = 0x7f11dc70f8c0 <g_cclosure_marshal_VOID__PARAM>
                marshal_data = 0x0
                in_marshal = 0
                real_closure = 0x55d46f0a0d50
                __FUNCTION__ = "g_closure_invoke"
    #4  0x00007f11dc7204f4 in signal_emit_unlocked_R (node=node@entry=0x55d46e3b0b90, detail=detail@entry=807, instance=instance@entry=0x7f11c000c380, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffdda655540) at ../gobject/gsignal.c:3635
                tmp = <optimized out>
                handler = 0x55d46f314580
                accumulator = 0x0
                emission = {next = 0x0, instance = 0x7f11c000c380, ihint = {signal_id = 1, detail = 807, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 0x4 [void]}
                class_closure = 0x55d46e3b0ef0
                hlist = <optimized out>
                handler_list = 0x55d46f314580
                return_accu = 0x0
                accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 1
                max_sequential_handler_number = 7061
                return_value_altered = 1
    #5  0x00007f11dc72934e in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffdda655720) at ../gobject/gsignal.c:3391
                instance_and_params = 0x7ffdda655540
                signal_return_type = <optimized out>
                param_values = 0x7ffdda655558
                node = <optimized out>
                i = <optimized out>
                n_params = <optimized out>
                __FUNCTION__ = "g_signal_emit_valist"
#7  0x00007f11dc711204 in g_object_dispatch_properties_changed (object=0x7f11c000c380 [SoupConnection], n_pspecs=<optimized out>, pspecs=<optimized out>) at ../gobject/gobject.c:1088
        i = <optimized out>
#8  0x00007f11dc710ade in g_object_notify_queue_thaw (object=object@entry=0x7f11c000c380 [SoupConnection], nqueue=nqueue@entry=0x55d46f358910) at ../gobject/gobject.c:296
        pspecs_mem = {0x55d46f113bb0 [GParamEnum], 0x38, 0x7f11c000c390, 0x0, 0x55d46f113bb0 [GParamEnum], 0x55d46f113bb0 [GParamEnum], 0x0, 0x38, 0x7f11c000c390, 0x0, 0x0, 0x7f11dc606537, 0x7f11c000c380 [SoupConnection], 0x0, 0x55d46e9cf8e0 [SoupSession], 0x7f11c000c390}
        pspecs = 0x7ffdda655830
        free_me = 0x0
        slist = <optimized out>
        n_pspecs = 1
        __FUNCTION__ = "g_object_notify_queue_thaw"
#9  0x00007f11dc71387b in g_object_thaw_notify (object=0x7f11c000c380 [SoupConnection]) at ../gobject/gobject.c:1325
        nqueue = 0x55d46f358910
        __FUNCTION__ = "g_object_thaw_notify"
#10 0x00007f11dbda684f in soup_connection_set_state (conn=<optimized out>, state=<optimized out>) at ../libsoup/soup-connection.c:721
        priv = <optimized out>
        __FUNCTION__ = "soup_connection_set_state"
#11 0x00007f11dbdc73da in soup_session_unqueue_item (session=0x55d46e9cf8e0 [SoupSession], item=0x55d46f419b40) at ../libsoup/soup-session.c:1489
        priv = 0x55d46e9cf7e0
        host = <optimized out>
        dedicated_conn = 0x0
#12 0x00007f11dbdcb365 in soup_session_process_queue_item (loop=<optimized out>, should_cleanup=<optimized out>, item=<optimized out>, session=<optimized out>) at ../libsoup/soup-session.c:2040
        __FUNCTION__ = "soup_session_process_queue_item"
        __FUNCTION__ = "soup_session_process_queue_item"
#13 0x00007f11dbdcb365 in soup_session_process_queue_item (session=<optimized out>, item=0x55d46f419b40, should_cleanup=<optimized out>, loop=<optimized out>) at ../libsoup/soup-session.c:1964
        __FUNCTION__ = "soup_session_process_queue_item"
#14 0x00007f11dbdcbd58 in async_run_queue (session=session@entry=0x55d46e9cf8e0 [SoupSession]) at ../libsoup/soup-session.c:2082
        priv = 0x55d46e9cf7e0
        item = 0x55d46f419b40
        msg = <optimized out>
        try_cleanup = <optimized out>
        should_cleanup = 0
#15 0x00007f11dbdcbdfa in idle_run_queue (user_data=user_data@entry=0x55d46f3d3c40) at ../libsoup/soup-session.c:2109
        wref = 0x55d46f3d3c40
        session = 0x55d46e9cf8e0 [SoupSession]
#16 0x00007f11dc6217cb in g_idle_dispatch (source=source@entry=0x55d46e5d2d90, callback=0x7f11dbdcbde0 <idle_run_queue>, user_data=0x55d46f3d3c40) at ../glib/gmain.c:5627
        again = <optimized out>
#17 0x00007f11dc624ecd in g_main_dispatch (context=0x55d46e3e1e60) at ../glib/gmain.c:3189
        dispatch = <optimized out>
        prev_source = 0x0
        was_in_call = <optimized out>
        user_data = 0x55d46f3d3c40
        callback = 0x7f11dbdcbde0 <idle_run_queue>
        cb_funcs = 0x7f11dc6f7280 <g_source_callback_funcs>
        cb_data = 0x55d46e4011d0
        need_destroy = <optimized out>
        source = 0x55d46e5d2d90
        current = 0x55d46e435ae0
        i = 0
        __FUNCTION__ = "g_main_dispatch"
#18 0x00007f11dc624ecd in g_main_context_dispatch (context=context@entry=0x55d46e3e1e60) at ../glib/gmain.c:3854
#19 0x00007f11dc625260 in g_main_context_iterate (context=0x55d46e3e1e60, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3927
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x55d46f0d8f40
#20 0x00007f11dc625593 in g_main_loop_run (loop=0x55d46e435f90) at ../glib/gmain.c:4123
        __FUNCTION__ = "g_main_loop_run"
#21 0x00007f11dce42f2d in gtk_main () at gtkmain.c:1323
        loop = 0x55d46e435f90
#22 0x00007f11dd7025a8 in _mate_panel_applet_factory_main_internal (factory_id=<optimized out>, out_process=1, applet_type=0x55d46e42da00 [MatePanelApplet/GtkEventBox/GtkBin/GtkContainer/GtkWidget/GInitiallyUnowned], callback=<optimized out>, user_data=0x0) at mate-panel-applet.c:2344
        factory = 0x55d46e416c60 [MatePanelAppletFactory]
        closure = 0x55d46e42db50
        __func__ = "_mate_panel_applet_factory_main_internal"
#23 0x000055d46dedae46 in main (argc=<optimized out>, argv=<optimized out>) at clock.c:3423
        context = 0x55d46e3a9fd0
        error = 0x0
        retval = <optimized out>
```
So, i assume it is more an issue with libmateweather.

**Comment by raveit65** [comment]
Reverting https://github.com/mate-desktop/libmateweather/commit/4cad2cfe818be68e2eb3ef038ab6177cf2fa0bc4 seems to fix the issue.
