### ISSUE TITLE
Security Issue: Null Dereference 

### ISSUE THREAD

**Issue by junorouse** [mate-desktop/mate-panel#1145]
#### Expected behaviour

1. should handle null ptr gracefully.

#### Actual behaviour

```
$ gdb -q python2
Reading symbols from python2...(no debugging symbols found)...done.
(gdb) r mate-menu.py
Starting program: /usr/bin/python2 mate-menu.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3809700 (LWP 17039)]
[New Thread 0x7ffff3008700 (LWP 17040)]
[New Thread 0x7ffff2484700 (LWP 17041)]

(mate-menu.py:17035): GLib-GIO-CRITICAL **: 10:54:46.882: g_dbus_connection_register_object: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed

Thread 1 "mate-menu" received signal SIGSEGV, Segmentation fault.
0x00007ffff2761d51 in ?? () from /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
(gdb) x/10i $rip
=> 0x7ffff2761d51:	mov    0x8(%rdx),%rdx
   0x7ffff2761d55:	callq  0x7ffff275f340 <g_printerr@plt>
   0x7ffff2761d5a:	mov    (%rsp),%rdi
   0x7ffff2761d5e:	callq  0x7ffff275fdb0 <g_error_free@plt>
   0x7ffff2761d63:	jmp    0x7ffff2761d20
   0x7ffff2761d65:	nopl   (%rax)
   0x7ffff2761d68:	xor    %esi,%esi
   0x7ffff2761d6a:	lea    0x522f(%rip),%rdi        # 0x7ffff2766fa0
   0x7ffff2761d71:	callq  0x7ffff275f270 <g_dbus_node_info_new_for_xml@plt>
   0x7ffff2761d76:	mov    %rax,0x92cb(%rip)        # 0x7ffff276b048
(gdb) i r $rdx
rdx            0x0                 0
(gdb) bt
#0  0x00007ffff2761d51 in  () at /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
#1  0x00007ffff76c1bfa in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff76c33d4 in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff76c3709 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff2764a55 in  () at /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
#5  0x00007ffff7377379 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007ffff7500dd8 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff75011c8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff75014c2 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff42c3715 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff2762713 in  () at /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
#11 0x00007ffff76708ee in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#12 0x00007ffff76702bf in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#13 0x00007ffff7726845 in  () at /usr/lib/python2.7/dist-packages/gi/_gi.x86_64-linux-gnu.so
#14 0x00007ffff771dc38 in  () at /usr/lib/python2.7/dist-packages/gi/_gi.x86_64-linux-gnu.so
#15 0x0000555555626883 in PyObject_Call ()
#16 0x000055555564a502 in PyEval_EvalFrameEx ()
#17 0x0000555555642866 in PyEval_EvalCodeEx ()
#18 0x00005555556421f9 in PyEval_EvalCode ()
#19 0x0000555555674e2f in  ()
#20 0x000055555566fd20 in PyRun_FileExFlags ()
#21 0x000055555566f6ca in PyRun_SimpleFileExFlags ()
#22 0x0000555555610188 in Py_Main ()
#23 0x00007ffff7a4a09b in __libc_start_main () at /lib/x86_64-linux-gnu/libc.so.6
#24 0x000055555560faea in _start ()

```

#### Steps to reproduce the behaviour

1. `gdbus call -e -d org.mate.panel.applet.MateMenuAppletFactory -o /org/mate/panel/applet/MateMenuAppletFactory -m org.mate.panel.applet.AppletFactory.GetApplet '!@#$' 2147483647 '{"aaaaa":<"bbbb">}'`
2. It crashed.

#### MATE general version

`/usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1.0.1`

#### Package version

`/usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1.0.1`

#### Linux Distribution

Debian GNU/Linux 10

#### Link to downstream report of your Distribution

N/A

**Comment by raveit65** [comment]
Does the issue still exists?
