### ISSUE TITLE
segfault on removing classic menu from panel

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#1185]
#### Expected behaviour
Note that the actual problem might be in mate-menus and not mate-panel but not sure:
adding and removing classic menu (menubar) from panel would work normally

#### Actual behaviour
Panel crashes with segfault (backtrace below) on removal of classic menu. Adding and removing compact menu works fine

#### Steps to reproduce the behaviour
Install mate-menus 1.25 if not already installed. Restart mate-panel
Add and then remove classic menubar from panel. 
panel crashes with a segfault
Roll mate-menus back to 1.24
Add and then remove classic menubar from panel. 
panel keeps running

#### MATE general version
1.25

#### Package version
local build from git master 12-25-2020

#### Linux Distribution
Debian Unstable with locally built gtk 3.24.3 and glib 2.67.0 

#### Link to bugreport of your Distribution (requirement)
None as this is a locally compiled package rather than Debian's build

**Comment by lukefromdc** [comment]
Got this backtrace, note that with gcc10 for some reason I am not getting debugging symbols installed by a local "make install" of mate-panel with my normal build options
Build options:

`./autogen.sh  --with-in-process-applets=wncklet,clock,fish,notification-area --prefix=/usr libdir=/usr/lib/x86_64-linux-gnu --sysconfdir=/etc --enable-shared=yes --enable-static=no --disable-maintainer-mode --disable-schemas-compile
`

Backtrace:
```

Thread 1 "mate-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff70eee66 in g_hash_table_remove_all ()
   from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) thread apply all bt full

Thread 6 (Thread 0x7fffe2d46700 (LWP 80001) "dconf worker"):
#0  0x00007ffff6c8139f in __GI___poll (fds=0x555555969970, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff71006a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff71007af in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6a1a7ed in  () at /usr/lib/x86_64-linux-gnu/libdconf.so.1
#4  0x00007ffff71286bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736998958848, -4537428888899512156, 140737488342654, 140737488342655, 140736998956160, 8396800, 4537400676192131236, 4537446567566022820}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c8bd8f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ffff0cbe700 (LWP 79804) "pool-mate-panel"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff714fab2 in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.--Type <RET> for more, q to quit, c to continue without paging--c
so.0
#2  0x00007ffff70d14e1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff70d1ac2 in g_async_queue_timeout_pop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7129009 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff71286bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737233282816, -4537428888899512156, 140737488346734, 140737488346735, 140737233280128, 8396800, 4537431466812676260, 4537446567566022820}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007ffff6c8bd8f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ffff1e0d700 (LWP 79803) "dconf worker"):
#0  0x00007ffff6c8139f in __GI___poll (fds=0x5555557dba50, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff71006a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff71007af in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff1e4438d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007ffff71286bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737251432192, -4537428888899512156, 140737488347246, 140737488347247, 140737251429504, 8396800, 4537433484910434468, 4537446567566022820}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c8bd8f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ffff26aa700 (LWP 79787) "gdbus"):
#0  0x00007ffff6c8139f in __GI___poll (fds=0x5555556ab5f0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff71006a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff71009eb in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7349896 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff71286bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737260463872, -4537428888899512156, 140737488344446, 140737488344447, 140737260461184, 8396800, 4537434496912103588, 4537446567566022820}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c8bd8f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffff2eab700 (LWP 79786) "gmain"):
#0  0x00007ffff6c8139f in __GI___poll (fds=0x555555698350, nfds=2, timeout=2026) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff71006a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff71007af in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7100801 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff71286bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737268856576, -4537428888899512156, 140737488344078, 140737488344079, 140737268853888, 8396800, 4537435594813118628, 4537446567566022820}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c8bd8f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff55dbf00 (LWP 79782) "mate-panel"):
#0  0x00007ffff70eee66 in g_hash_table_remove_all () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff74185e5 in  () at /usr/lib/x86_64-linux-gnu/libmate-menu.so.2
#2  0x00007ffff7418659 in  () at /usr/lib/x86_64-linux-gnu/libmate-menu.so.2
#3  0x00007ffff710038f in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7100708 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff71009eb in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff78fbef5 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x0000555555579118 in main ()
(gdb) 

```

**Comment by lukefromdc** [comment]
Closing this, will open new issue at mate-menus
