### ISSUE TITLE
Window list, tray rendered incompletely until restart after moving to another panel

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#504]
Using mate-panel 1.17 and GTK 3.22, if I drag the window list or tray from one panel to another, the drop works but only the grab handle is rendered until the panel is restarted. Dragging the window list to another panel can also crash the workspace switcher applet.
##

**Comment by raveit65** [comment]
yes, i see that with other applets too, ie. cpu-freq applet.

**Comment by raveit65** [comment]
And gtk+-3.20 is also affected.

**Comment by monsta** [comment]
@lukefromdc: yes, we got some new info on this in https://github.com/mate-desktop/mate-panel/issues/516.

**Comment by lukefromdc** [comment]
I still have no idea what causes this

**Comment by monsta** [comment]
I found out it's reproducible with GTK+ 3.14 and 3.18 as well. Not with all applet types though... A few special applet types like logout button, lock screen button, drawer, etc. are rendered on the new panel properly.

**Comment by monsta** [comment]
Surprise, I can reproduce it in 1.16 with GTK+2... :open_mouth:

**Comment by monsta** [comment]
Here's the backtrace from GTK+2 build of 1.16.

```gdb
(gdb) bt full
#0  0x00007f9691f15428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 3944
        selftid = 3944
#1  0x00007f9691f1702a in __GI_abort () at abort.c:89
        save_stage = 2
        act = 
          {__sigaction_handler = {sa_handler = 0x10004d11b, sa_sigaction = 0x10004d11b}, sa_mask = {__val = {0, 140284674413088, 3, 0, 140284670683708, 18446744073709551615, 0, 140733790577632, 7315242843790799616, 140, 140284671125245, 140284674070384, 140, 140733790567552, 140284706310528, 140}}, sa_flags = -1846105745, sa_restorer = 0x7f9692398ee1}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f9692337111 in g_thread_abort (status=<optimized out>, function=function@entry=0x7f9692398ee1 "pthread_setspecific")
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread-posix.c:77
#3  0x00007f96923376ca in g_private_set (key=key@entry=0x7f96925b9160 <g_log_depth>, value=value@entry=0x1)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread-posix.c:1075
        status = <optimized out>
#4  0x00007f96922f9991 in g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fff23986540)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmessages.c:1057
        domain = 0x0
        data = 0x0
        depth = 1
        log_func = 0x7f96922f9220 <g_log_default_handler>
        domain_fatal_mask = <optimized out>
        masquerade_fatal = 0
        test_level = G_LOG_LEVEL_CRITICAL
        was_fatal = <optimized out>
        was_recursion = <optimized out>
        msg = 0x55696429b670 "mate_panel_applet_get_background: assertion 'PANEL_IS_APPLET (applet)' failed"
        msg_alloc = 0x55696429b670 "mate_panel_applet_get_background: assertion 'PANEL_IS_APPLET (applet)' failed"
        i = 3
#5  0x00007f96922f9bcf in g_log (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_CRITICAL, format=format@entry=0x7f9692344374 "%s: assertion '%s' failed") at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmessages.c:1119
Python Exception <class 'gdb.error'> Attempt to dereference a generic pointer.: 
#6  0x00007f96922f9c09 in g_return_if_fail_warning (log_domain=log_domain@entry=0x0, pretty_function=pretty_function@entry=0x7f9693d6ca00 <__func__.56627> "mate_panel_applet_get_background", expression=expression@entry=0x7f9693d6c3fa "PANEL_IS_APPLET (applet)")
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmessages.c:1134
#7  0x00007f9693d6a629 in mate_panel_applet_get_background (applet=0x5569640d7310, color=0x7fff239866c0, pixmap=0x7fff239866b8) at mate-panel-applet.c:1665
        applet = 0x5569640d7310
        color = 0x7fff239866c0
        pixmap = 0x7fff239866b8
#8  0x00007f9693d6abed in mate_panel_applet_handle_background (applet=applet@entry=0x5569640d7310) at mate-panel-applet.c:1790
        type = <optimized out>
        color = {pixel = 6, red = 0, green = 0, blue = 34585}
        pixmap = 0x6
        __func__ = "mate_panel_applet_handle_background"
#9  0x00007f9693d6afa6 in mate_panel_applet_set_background_string (applet=0x5569640d7310, background=0x7f968000d8d8 "none:") at mate-panel-applet.c:1702
        background = 0x7f968000d8d8 "none:"
        applet = 0x5569640d7310
#10 0x00007f9693d6b145 in set_property_cb (connection=<optimized out>, sender=<optimized out>, object_path=object_path@entry=0x7f968000d690 "/org/mate/panel/applet/WorkspaceSwitcherApplet/2", interface_name=interface_name@entry=0x556964169a90 "org.mate.panel.applet.Applet", property_name=property_name@entry=0x7f968000d8cd "Background", value=value@entry=0x7f9680008600, error=0x7fff23986778, user_data=0x5569640d7310) at mate-panel-applet.c:2456
        applet = 0x5569640d7310
#11 0x00007f96928e2268 in invoke_set_property_in_idle_cb (_data=0x7f968000d710) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gio/gdbusconnection.c:4169
---Type <return> to continue, or q <return> to quit---
        error = 0x0
        reply = <optimized out>
        value = 0x7f9680008600
        __func__ = "invoke_set_property_in_idle_cb"
#12 0x00007f96922f304a in g_main_context_dispatch (context=0x556964093df0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3154
        dispatch = 0x7f96922efb00 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x7f968000d710
        callback = 0x7f96928e21c0 <invoke_set_property_in_idle_cb>
        cb_funcs = <optimized out>
        cb_data = 0x7f96800064c0
        need_destroy = <optimized out>
        source = 0x7f968000d800
        current = 0x5569640c80c0
        i = 3
#13 0x00007f96922f304a in g_main_context_dispatch (context=context@entry=0x556964093df0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3769
#14 0x00007f96922f33f0 in g_main_context_iterate (context=0x556964093df0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3840
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x5569640cdc60
#15 0x00007f96922f3712 in g_main_loop_run (loop=0x5569640cdc20) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4034
        __func__ = "g_main_loop_run"
#16 0x00007f96933c16a7 in IA__gtk_main () at /build/gtk+2.0-KsZKkB/gtk+2.0-2.24.30/gtk/gtkmain.c:1282
        tmp_list = 0x0
        functions = 0x0
        init = <optimized out>
        loop = 0x5569640cdc20
#17 0x00007f9693d6b573 in mate_panel_applet_factory_main (factory_id=<optimized out>, out_process=1, applet_type=93911138469120, callback=<optimized out>, user_data=0x0) at mate-panel-applet.c:2620
        factory = 0x55696409d200 [MatePanelAppletFactory]
        closure = 0x5569640c8680
        __func__ = "mate_panel_applet_factory_main"
#18 0x0000556963349f05 in main (argc=1, argv=0x7fff23986ab8) at wncklet.c:143
        context = 0x556964056ed0
        error = 0x0
        retval = <optimized out>
(gdb) 
```
I can't tell which applet it was, I just attached gdb to `/usr/lib/mate-panel/wnck-applet` process which is responsible for Show Desktop button, window list and workspace switcher. There is a single process, so any of these applets might crash if you move any other of them to another panel.

**Comment by monsta** [comment]
Ok, so it got broken in https://github.com/mate-desktop/mate-panel/commit/225702b3c6a609065465c66f0f2739fc1d2184a9.

**Comment by monsta** [comment]
Fixed it in https://github.com/mate-desktop/mate-panel/pull/584. Rendering issue is gone, wnck-applet crash seems to be gone too. Need some more testing to be sure.
