### ISSUE TITLE
[ubuntu] MATE panel crashed when using global menu

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/mate-panel#562]
If I switch panel layout to "Mutiny", then open Terminal (for example) window and click on Global Menu - terminal and panel will crashed. I use Ubuntu MATE 17.04.

**Comment by lukefromdc** [comment]
I see this is mate-panel 1.18.1 with GTK 3.22.11 if just updated. Mate-panel, mate-desktop, and mate-settings-daemon just got some work to deal with another globalmenu issue in git master (version 1.19).  If you can build these three packages and try them out you could determine if this is still an issue or not.

Also, can you post whatever errors mate-panel put in syslog or .xsession-errors here? They will help those here who are working with the global menu support.

**Comment by Sunderland93** [comment]
Ok, I will try 1.19. Here is xsession-errors log

```
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/sunderland93/.Xauthority
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge:unity-gtk-module
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
dbus-update-activation-environment: setting LANG=ru_RU.UTF-8
dbus-update-activation-environment: setting GDM_LANG=ru
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting COMPIZ_CONFIG_PROFILE=mate
dbus-update-activation-environment: setting MANDATORY_PATH=/usr/share/gconf/mate.mandatory.path
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/sunderland93
dbus-update-activation-environment: setting USER=sunderland93
dbus-update-activation-environment: setting DESKTOP_SESSION=mate
dbus-update-activation-environment: setting DEFAULTS_PATH=/usr/share/gconf/mate.default.path
dbus-update-activation-environment: setting PWD=/home/sunderland93
dbus-update-activation-environment: setting HOME=/home/sunderland93
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/mate:/usr/share/mate:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=mate
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge:unity-gtk-module
dbus-update-activation-environment: setting UBUNTU_MENUPROXY=1
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting XDG_CURRENT_DESKTOP=MATE
dbus-update-activation-environment: setting QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
dbus-update-activation-environment: setting SHLVL=1
dbus-update-activation-environment: setting LANGUAGE=ru
dbus-update-activation-environment: setting GDMSESSION=mate
dbus-update-activation-environment: setting LOGNAME=sunderland93
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting XAUTHORITY=/home/sunderland93/.Xauthority
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
dbus-update-activation-environment: setting XDG_CONFIG_DIRS=/etc/xdg/xdg-mate:/etc/xdg
dbus-update-activation-environment: setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
dbus-update-activation-environment: setting _=/usr/bin/dbus-update-activation-environment
** Message: couldn't access control socket: /run/user/1000/keyring/control: Нет такого файла или каталога
mate-session[1104]: WARNING: Unable to find provider '' of required component 'dock'
Предупреждение менеджера окон: Log level 16: g_object_set_valist: object class 'MetaFrames' has no property named 'type'

** (mate-panel:1449): CRITICAL **: appmenu_app_menu_bar_replace_menu: assertion 'menu != NULL' failed

(mate-settings-daemon:1402): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(mate-volume-control-applet:1648): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
sys:1: PyGIWarning: Caja was imported without specifying a version first. Use gi.require_version('Caja', '2.0') before import to ensure that the right version gets loaded.
** Message: Initializing gksu extension...

** (caja:1547): CRITICAL **: caja_menu_provider_get_background_items: assertion 'CAJA_IS_MENU_PROVIDER (provider)' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Предупреждение менеджера окон: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3600007 ()
Предупреждение менеджера окон: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Panel leaving: a new panel shell is starting.

(mate-panel:1894): EggSMClient-CRITICAL **: egg_sm_client_set_mode: assertion 'global_client == NULL || global_client_mode == EGG_SM_CLIENT_MODE_DISABLED' failed
Cannot register the panel shell: there is already one running.
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez.obex': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/plugins/BasePlugin.py", line 54, in _load
    self.on_load(parent)
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/TransferService.py", line 155, in on_load
    self._manager = obex.Manager()
  File "/usr/lib/python3/dist-packages/blueman/bluez/obex/Manager.py", line 20, in __init__
    if self.__class__.get_interface_version()[0] < 5:
  File "/usr/lib/python3/dist-packages/blueman/bluez/obex/Base.py", line 23, in get_interface_version
    obj = dbus.SessionBus().get_object('org.bluez.obex', '/')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.bluez.obex.service not found.
Exception ignored in: <bound method Base.__del__ of <Manager.Manager object at 0x7f8eaef8ad38 (uninitialized at 0x(nil))>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/bluez/obex/Base.py", line 47, in __del__
    self.__signals.DisconnectAll()
AttributeError: 'Manager' object has no attribute '_Base__signals'
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out
ERROR:dbus.proxies:Introspect error on org.bluez:/org/bluez: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out
ERROR:dbus.proxies:Introspect error on org.bluez:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out

** (caja:1547): CRITICAL **: caja_menu_provider_get_background_items: assertion 'CAJA_IS_MENU_PROVIDER (provider)' failed

(caja:1547): Gtk-CRITICAL **: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:1547): Gtk-CRITICAL **: gtk_window_set_type_hint: assertion 'GTK_IS_WINDOW (window)' failed
sys:1: PyGIWarning: Caja was imported without specifying a version first. Use gi.require_version('Caja', '2.0') before import to ensure that the right version gets loaded.
** Message: Initializing gksu extension...

** (caja:2011): CRITICAL **: caja_menu_provider_get_background_items: assertion 'CAJA_IS_MENU_PROVIDER (provider)' failed

** (caja:2011): CRITICAL **: caja_menu_provider_get_background_items: assertion 'CAJA_IS_MENU_PROVIDER (provider)' failed

(caja:2011): Gtk-CRITICAL **: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:2011): Gtk-CRITICAL **: gtk_window_set_type_hint: assertion 'GTK_IS_WINDOW (window)' failed
sys:1: PyGIWarning: Caja was imported without specifying a version first. Use gi.require_version('Caja', '2.0') before import to ensure that the right version gets loaded.
** Message: Initializing gksu extension...

** (caja:2030): CRITICAL **: caja_menu_provider_get_background_items: assertion 'CAJA_IS_MENU_PROVIDER (provider)' failed
```

**Comment by lukefromdc** [comment]
Culprit might be

`** (mate-panel:1449): CRITICAL **: appmenu_app_menu_bar_replace_menu: assertion 'menu != NULL' failed
`
Also see these warnings from Caja in your log;
```

** (caja:2011): CRITICAL **: caja_menu_provider_get_background_items: assertion 'CAJA_IS_MENU_PROVIDER (provider)' failed

** (caja:2011): CRITICAL **: caja_menu_provider_get_background_items: assertion 'CAJA_IS_MENU_PROVIDER (provider)' failed
```

Wonder if this relates in any way to this now-closed issue:
https://github.com/mate-desktop/mate-panel/issues/549
which was closed by
https://github.com/mate-desktop/mate-panel/pull/550
in git master?  I can't test that because I don't have any of the global menu packages installed and am on Debian Unstable. Hopefully others here can, now that we've got some info.

**Comment by raveit65** [comment]
@rilian-la-te 
Can you please take a look into it?

**Comment by rilian-la-te** [comment]
In weekend. I think he is catched variant of https://github.com/rilian-la-te/vala-panel-appmenu/issues/54. 

I suggest try latest master of vala-panel-appmenu. 
What version he is using?

**Comment by Sunderland93** [comment]
> I suggest try latest master of vala-panel-appmenu.
What version he is using?

This is not vala-panel-appmenu, but only "Mutiny" panel layout which contains global menu. After installing vala-panel-appmenu from PPA and add applet into panel - it's works fine, but panel has 2 global menu's.

**Comment by lukefromdc** [comment]
Where does Mutiny get its support for global menus from? Panel layouts don't install new software that I've ever seen, only configure existing software. Is this based on using Ubuntu's Unity module referenced in the earlier round of globalmenu work?

**Comment by raveit65** [comment]
I heard that the old globalmenu applet in ubuntu-mate is quite broken and vala-panel-appmenu is the replacement.
@flexiondotorg ^^^^
And is this really a mate-panel problem?
@Sunderland93 
Where is the ubuntu bugreport aggainst the application?

**Comment by alunux** [comment]
@lukefromdc it's from topmenu-gtk, cmiiw.

**Comment by flexiondotorg** [comment]
TopMenu is busted and will be dropped from the Ubuntu archive in 17.10. 

The new hostness is vala-panel-appmenu and Ubuntu MATE will use it in 17.10.

That said, neither projects are MATE components, so this bug is not relevant to MATE.
